# Generated by Django 4.0 on 2021-12-24 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('max_examinees', models.IntegerField()),
                ('time_set', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationVenueAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('school_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=20)),
                ('school_category', models.CharField(choices=[('High School', 'High School'), ('College', 'College'), ('University', 'University'), ('Other', 'Other')], max_length=40)),
                ('district', models.CharField(choices=[('District I', 'District I'), ('District II', 'District II'), ('Other', 'Other')], max_length=40)),
                ('school_address', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30)),
                ('middlename', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=7)),
                ('date_of_birth', models.DateField()),
                ('contactno', models.CharField(default='', max_length=11)),
                ('date_registered', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(default='', max_length=6, unique=True)),
                ('predicted_performance', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_type', models.CharField(choices=[('English', 'English'), ('Math', 'Math'), ('Science', 'Science')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default='', max_length=10)),
                ('college_code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('room_code', 'college_code'), name='Room x College Constraint'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_website.student'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_website.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='registration_website.school'),
        ),
        migrations.AddField(
            model_name='examinationvenueassignment',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_website.examination'),
        ),
        migrations.AddField(
            model_name='examinationvenueassignment',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_website.venue'),
        ),
        migrations.AddConstraint(
            model_name='examinationvenueassignment',
            constraint=models.UniqueConstraint(fields=('examination', 'venue'), name='room_college constraint'),
        ),
    ]
