# Generated by Django 4.0 on 2021-12-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_website', '0004_student_strand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(default='', max_length=50),
        ),
    ]
