# Generated by Django 4.0 on 2021-12-29 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration_website', '0005_alter_student_strand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['school_name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_name']},
        ),
        migrations.AddField(
            model_name='student',
            name='applicant_type',
            field=models.CharField(choices=[('Senior High School Graduating Student', 'Senior High School Graduating Student'), ('Senior High School Graduate', 'Senior High School Graduate'), ('College Student', 'College Student')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='combined_parent_income',
            field=models.CharField(choices=[('< 11,000', '< 11,000'), ('11,000 - 22,000', '11,000 - 22,000'), ('22,000 - 44,000', '22,000 - 44,000'), ('44,000 - 77,000', '44,000 - 77,000'), ('77,000 - 132,000', '77,000 - 132,000'), ('132,000 - 220,000', '132,000 - 220,000'), ('> 220,000', '> 220,000')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='ethnicity',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='first_course',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='home_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_course',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='last_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='second_course',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='target_campus',
            field=models.CharField(choices=[('Main Campus', 'Main Campus'), ('ESU Alicia', 'ESU Alicia'), ('ESU Aurora', 'ESU Aurora'), ('ESU Curuan', 'ESU Curuan'), ('ESU Imelda', 'ESU Imelda'), ('ESU Ipil', 'ESU Ipil'), ('ESU Malangas', 'ESU Malangas'), ('ESU Molave', 'ESU Molave'), ('ESU Pagadian', 'ESU Pagadian'), ('ESU Siay', 'ESU Siay'), ('ESU Tungawan', 'ESU Tungawan')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='times_taken',
            field=models.CharField(default='', max_length=20),
        ),
    ]
