# Generated by Django 4.0 on 2022-01-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_website', '0007_college_alter_student_applicant_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
