# Generated by Django 4.0 on 2022-01-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_website', '0008_alter_college_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationvenueassignment',
            name='current_examinees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examinationvenueassignment',
            name='max_examinees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='examination_assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='registration_website.examinationvenueassignment'),
            preserve_default=False,
        ),
    ]
