# Generated by Django 4.0 on 2022-01-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_website', '0011_alter_examinationvenueassignment_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationvenueassignment',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_venues', to='registration_website.examination'),
        ),
    ]
