# Generated by Django 4.0 on 2022-01-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_website', '0013_alter_venue_college_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='registration_website.student'),
        ),
    ]
